import {
    COLUMN_MAP as SOURCE_COLUMN_MAP,
    NEWSLETTER_COLUMN as SOURCE_NEWSLETTER_COLUMN,
    RENDER_NEWSLETTER as SOURCE_RENDER_NEWSLETTER,
} from 'SourceComponent/Footer/Footer.config';

// TODO: implement RENDER_NEWSLETTER
export const RENDER_NEWSLETTER = SOURCE_RENDER_NEWSLETTER;

// TODO: implement NEWSLETTER_COLUMN
export const NEWSLETTER_COLUMN = SOURCE_NEWSLETTER_COLUMN;

// TODO: implement COLUMN_MAP
export const COLUMN_MAP = SOURCE_COLUMN_MAP;
